export type Link = { label: string; href: string };
export type Project = { slug: string; name: string; kind: string; summary: string; detail: string; status: string; tags: string[]; href: string; repo: string; featured?: boolean };
export type Research = { slug: string; title: string; year: string; summary: string; detail: string; links: Link[]; tags: string[] };

export const projects: Project[] = [
  { slug: "resalign", name: "ResAlign AI", kind: "Product / career intelligence", summary: "A career copilot for fit, preparedness, and alignment—not another apply-to-everything button.", detail: "ResAlign started from a simple question: can a system help someone decide whether a role is worth pursuing before it asks them to apply? It turns resumes and job descriptions into a more honest conversation about readiness, evidence, and next steps.", status: "In the wild", tags: ["AI systems", "Product", "Evaluation"], href: "https://resalign.com", repo: "", featured: true },
  { slug: "harnessbox", name: "HarnessBox", kind: "Open source / agent infrastructure", summary: "Sandbox and harness primitives for coding agents. Zero dependencies, on purpose.", detail: "HarnessBox is an attempt to make the runtime around a coding agent legible: workspaces, sessions, mounts, and agent runtimes with small, composable primitives.", status: "Building", tags: ["Agents", "Python", "Open source"], href: "https://github.com/Nikhil-Kadapala/HarnessBox", repo: "https://github.com/Nikhil-Kadapala/HarnessBox", featured: true },
  { slug: "agentic-rag", name: "agentic-rag", kind: "Research engineering", summary: "Multimodal agentic RAG with a real evaluation harness. “It felt pretty good” is not a metric.", detail: "This project is a working surface for experimenting with retrieval, tool use, and multimodal context while keeping evaluation close to the system being built.", status: "Open source", tags: ["RAG", "Multimodal", "Evals"], href: "https://github.com/Nikhil-Kadapala/agentic-rag", repo: "https://github.com/Nikhil-Kadapala/agentic-rag", featured: true },
  { slug: "checkthat", name: "CheckThat", kind: "Paper → package", summary: "Noisy social posts to concise, checkable claims—class project to paper to pip install.", detail: "A claim-extraction system for fact-checkers, built around the gap between a high automatic score and a claim a human can actually work with.", status: "Published", tags: ["NLP", "Claim extraction", "Research"], href: "https://github.com/Nikhil-Kadapala/checkthat", repo: "https://github.com/Nikhil-Kadapala/checkthat", featured: true },
  { slug: "rational-neural-nets", name: "Rational Neural Nets", kind: "Interpretability", summary: "Teaching neural networks to rationalize sentiment with human annotations and LIME.", detail: "An earlier exploration of whether a model can show its work in a way a person would recognize.", status: "Archive", tags: ["Interpretability", "NLP"], href: "https://github.com/Nikhil-Kadapala/Rational-NeuralNets", repo: "https://github.com/Nikhil-Kadapala/Rational-NeuralNets" },
];

export const research: Research[] = [{ slug: "claim-extraction-checkthat-2025", title: "UNH at CheckThat! 2025: Fine-tuning Vs Prompting in Claim Extraction", year: "2025", summary: "Extracting one succinct, checkable claim from a messy social post—and measuring the gap between benchmark scores and usefulness.", detail: "We compared fine-tuning and prompting setups for claim extraction. FLAN-T5 won on METEOR, while iterative self-refinement sometimes produced claims a fact-checker would actually want to work with. That gap is the whole plot: evaluation has to stay connected to the user and the work the system is meant to support.", links: [{ label: "Paper", href: "https://arxiv.org/abs/2509.06883" }, { label: "CEUR", href: "https://ceur-ws.org/Vol-4038/paper_103.pdf" }, { label: "Writeup", href: "https://github.com/Nikhil-Kadapala/checkthat-research-paper" }], tags: ["Claim extraction", "Evaluation", "CLEF 2025"] }];
